scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
    - targets:
      - 192.168.56.102:9090
- job_name: pushgateway
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.56.102:9091

